# Generated by Django 3.0b1 on 2019-10-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.SlugField(allow_unicode=True, max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(allow_unicode=True, max_length=128)),
                ('markdown', models.TextField()),
                ('markdown_time', models.DateTimeField()),
                ('draft', models.TextField(blank=True, null=True)),
                ('draft_time', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='main.Tag')),
            ],
        ),
    ]
